### ISSUE TITLE
Can't run on MacOS with M1 

### ISSUE THREAD

**Issue by aqiao** [ccappetta/bidirectional_streaming_ai_voice#12]
Hi, when running on MacOS (M1) with Python 3.10, it throws below exception:

```
Traceback (most recent call last):
  File "/Users/test/Learning/bedrock/bidirectional_streaming_ai_voice/main.py", line 252, in <module>
    main()
  File "/Users/test/Learning/bedrock/bidirectional_streaming_ai_voice/main.py", line 227, in main
    recording, fs = record_audio()
  File "/Users/test/Learning/bedrock/bidirectional_streaming_ai_voice/main.py", line 81, in record_audio
    with sd.InputStream(callback=callback, samplerate=fs, channels=2, blocksize=int(fs * block_duration)):
  File "/Users/test/Learning/bedrock/bidirectional_streaming_ai_voice/installer-v2/venv/lib/python3.10/site-packages/sounddevice.py", line 1421, in __init__
    _StreamBase.__init__(self, kind='input', wrap_callback='array',
  File "/Users/test/Learning/bedrock/bidirectional_streaming_ai_voice/installer-v2/venv/lib/python3.10/site-packages/sounddevice.py", line 898, in __init__
    _check(_lib.Pa_OpenStream(self._ptr, iparameters, oparameters,
  File "/Users/test/Learning/bedrock/bidirectional_streaming_ai_voice/installer-v2/venv/lib/python3.10/site-packages/sounddevice.py", line 2747, in _check
    raise PortAudioError(errormsg, err)
sounddevice.PortAudioError: Error opening InputStream: Invalid number of channels [PaErrorCode -9998]
```
I tried to re-install `sounddevice` and `PortAudio`, it still doesn't work

**Comment by aqiao** [comment]
Changing the channels number to 1 fixed my issue
```
    with sd.InputStream(callback=callback, samplerate=fs, channels=1, blocksize=int(fs * block_duration)):
        while is_recording and len(audio_data) * block_duration < duration:
            sd.sleep(int(block_duration * 1000))
```
